[package]
name = "CharterCsv"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.31.0"
eframe = "0.31.0"
rfd = "0.15.2"
image = "0.25.5"
itertools = "0.12.1"
rusqlite = { version = "0.34", features = ["bundled"] }